
server:
  port: 8888
  
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SalmanKasheef/Microservices-Config-Server
          clone-on-start: true
          skip-ssl-validation: true

       
    